In [126]:
import pandas as pd

In [127]:
pd.set_option('display.max_columns', None)

In [128]:
df = pd.read_csv('new_retail_data.csv')

cols = ["Transaction_ID", "Customer_ID", "Zipcode", "Ratings", "Total_Purchases", 'Age']
df[cols] = df[cols].astype("Int64")

df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,9/18/2023,2023.0,September,22:03:55,3,108.028757,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,6.852900e+09,82072 Dawn Centers,Nottingham,England,99071,UK,19,Female,Low,Premium,12/31/2023,2023.0,December,8:42:04,2,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,8.362160e+09,4133 Young Canyon,Geelong,New South Wales,75929,Australia,48,Male,Low,Regular,4/26/2023,2023.0,April,4:06:29,3,354.477600,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,2.776752e+09,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,56,Male,High,Premium,5/8/2023,2023.0,May,14:55:17,7,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,9.098268e+09,5813 Lori Ports Suite 269,Bristol,England,48704,UK,22,Male,Low,Premium,1/10/2024,2024.0,January,16:54:07,2,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1,Chocolate cookies

In [ ]:
#Remove customers that have different emails for the same customer id
valid_ids = (
    df.groupby("Customer_ID")["Email"]
    .nunique()
    .eq(1)
)

df_clean = df[df["Customer_ID"].isin(valid_ids[valid_ids].index)]

df = df_clean.copy()

df_clean.head()

print(len(df))
print(len(df_clean))

10987
10987

In [131]:
customer_info_cols = ['Customer_ID', 'Name', 'Email', 'Phone', 'Address', 'City', 'State', 'Zipcode', 'Country', 'Age', 'Gender', 'Income', 'Customer_Segment']

In [132]:
#Save non-customer columns as transaction data columns
df_transactions = df.drop(columns=customer_info_cols[1:])

# Make transaction date and time into one timestamp column
df_transactions['Transaction_Date'] = pd.to_datetime(df_transactions['Date'] + ' ' + df_transactions['Time'])

#Also drop out Year, Month, Date columns
df_transactions = df_transactions.drop(columns=['Date', 'Time', 'Year', 'Month'])

#Show final transactions dataframe
df_transactions.head()

,Transaction_ID,Customer_ID,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products,Transaction_Date
8,4155845,80175,8,328.839302,2630.714413,Grocery,Nestle,Chocolate,Bad,Same-Day,Cash,Delivered,1,Dark chocolate,2024-01-06 14:38:26
15,4969987,64995,3,23.723901,71.171704,Books,Random House,Literature,Bad,Express,Credit Card,Pending,1,Drama,2023-06-15 23:24:22
22,9476855,42410,6,34.124266,204.745598,Books,Penguin Books,Non-Fiction,Average,Same-Day,PayPal,Processing,2,Self-help,2024-02-03 06:22:00
30,3413296,98256,3,159.804193,479.412580,Clothing,Adidas,Shoes,Good,Same-Day,Debit Card,Pending,3,Running shoes,2024-02-06 01:59:20
51,4580441,12911,3,394.606266,1183.818797,Grocery,Nestle,Chocolate,Excellent,Express,PayPal,Processing,5,White chocolate,2023-11-11 15:38:31

In [133]:
# Rearrange column order

# Specify the column to move and the desired new position (index)
column_to_move = 'Transaction_Date'
new_position = 2 # To move to the first position

# 1. Use pop() to remove the column and store its data
col_data = df_transactions.pop(column_to_move)

# 2. Use insert() to place the column at the desired position
df_transactions.insert(new_position, column_to_move, col_data)

print("New DataFrame columns:", df_transactions.columns)

df_transactions.head()

New DataFrame columns: Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Total_Purchases',
       'Amount', 'Total_Amount', 'Product_Category', 'Product_Brand',
       'Product_Type', 'Feedback', 'Shipping_Method', 'Payment_Method',
       'Order_Status', 'Ratings', 'products'],
      dtype='object')

,Transaction_ID,Customer_ID,Transaction_Date,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
8,4155845,80175,2024-01-06 14:38:26,8,328.839302,2630.714413,Grocery,Nestle,Chocolate,Bad,Same-Day,Cash,Delivered,1,Dark chocolate
15,4969987,64995,2023-06-15 23:24:22,3,23.723901,71.171704,Books,Random House,Literature,Bad,Express,Credit Card,Pending,1,Drama
22,9476855,42410,2024-02-03 06:22:00,6,34.124266,204.745598,Books,Penguin Books,Non-Fiction,Average,Same-Day,PayPal,Processing,2,Self-help
30,3413296,98256,2024-02-06 01:59:20,3,159.804193,479.412580,Clothing,Adidas,Shoes,Good,Same-Day,Debit Card,Pending,3,Running shoes
51,4580441,12911,2023-11-11 15:38:31,3,394.606266,1183.818797,Grocery,Nestle,Chocolate,Excellent,Express,PayPal,Processing,5,White chocolate

In [134]:
df_customer_info = df[customer_info_cols]

# Convert phone number from float to string
df_customer_info['Phone'] = df_customer_info['Phone'].fillna(0).astype('int64').astype('string')

df_customer_info.head()

C:\Users\urvij\AppData\Local\Temp\ipykernel_14472\2586289450.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_customer_info['Phone'] = df_customer_info['Phone'].fillna(0).astype('int64').astype('string')

,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment
8,80175,Diane Clark,Martin39@gmail.com,6219779557,8823 Mariah Heights Apt. 263,Wollongong,New South Wales,39820,Australia,46,Male,Medium,New
15,64995,Justin Lara,Jacob26@gmail.com,2683281702,3577 Cole Stream Apt. 351,Portsmouth,England,9845,UK,43,Male,Medium,Regular
22,42410,Anthony Rodriguez,Paula49@gmail.com,3745118170,585 Malik Lodge Suite 186,Portsmouth,England,83903,UK,21,Female,Low,Regular
30,98256,Steven Boyd,Sheryl18@gmail.com,5248581519,1719 Christina Heights Apt. 614,Portsmouth,England,43602,UK,26,Female,Low,Regular
51,12911,Chelsea Cummings,Daniel55@gmail.com,9050662623,336 Sara Run,Portsmouth,England,27283,UK,69,Male,High,Regular

In [135]:
# Write separated dataframes to CSV
df_transactions.to_csv('retail_transactions.csv', index=False)
df_customer_info.to_csv('retail_customers.csv', index=False)

In [136]:
# Show transaction dataset columns
df_transactions.columns.str.upper()

Index(['TRANSACTION_ID', 'CUSTOMER_ID', 'TRANSACTION_DATE', 'TOTAL_PURCHASES',
       'AMOUNT', 'TOTAL_AMOUNT', 'PRODUCT_CATEGORY', 'PRODUCT_BRAND',
       'PRODUCT_TYPE', 'FEEDBACK', 'SHIPPING_METHOD', 'PAYMENT_METHOD',
       'ORDER_STATUS', 'RATINGS', 'PRODUCTS'],
      dtype='object')

In [137]:
# Show customer info dataset columns
df_customer_info.columns.str.upper()

Index(['CUSTOMER_ID', 'NAME', 'EMAIL', 'PHONE', 'ADDRESS', 'CITY', 'STATE',
       'ZIPCODE', 'COUNTRY', 'AGE', 'GENDER', 'INCOME', 'CUSTOMER_SEGMENT'],
      dtype='object')

In [138]:
df_customer_info.dtypes

Customer_ID                  Int64
Name                        object
Email                       object
Phone               string[python]
Address                     object
City                        object
State                       object
Zipcode                      Int64
Country                     object
Age                          Int64
Gender                      object
Income                      object
Customer_Segment            object
dtype: object

In [140]:
df_clean.sample(1000).to_csv('retail_dataset_sample.csv', index=False)